---
abstract: 'Handling transaction tokens across forms'
author:
  - 'Hideo Kimura C<< <<hide<at>hide-k.net>> >>'
build_requires:
  Catalyst::Action::RenderView: 0
  Catalyst::Plugin::Session: 0
  Catalyst::Plugin::Session::State::Cookie: 0
  Catalyst::Runtime: 5.8
  ExtUtils::MakeMaker: 6.36
  Test::More: 0
  ok: 0
configure_requires:
  ExtUtils::MakeMaker: 6.36
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.06'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Catalyst-Controller-RequestToken
no_index:
  directory:
    - inc
    - t
requires:
  Digest: 0
  Scalar::Util: 0
resources:
  license: http://dev.perl.org/licenses/
  repository: git://github.com/hidek/Catalyst-Controller-RequestToken.git
version: 0.07
