---
abstract: 'Handling transaction token across forms'
author:
  - 'Hideo Kimura C<< <<hide<at>hide-k.net>> >>'
build_requires:
  Catalyst::Action::RenderView: 0
  Catalyst::Plugin::Session: 0
  Catalyst::Plugin::Session::State::Cookie: 0
  Catalyst::Runtime: 5.7
  ExtUtils::MakeMaker: 6.42
  Test::More: 0
  ok: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.84'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Catalyst-Controller-RequestToken
no_index:
  directory:
    - inc
    - t
requires:
  Digest: 0
  MRO::Compat: 0
  Scalar::Util: 0
resources:
  license: http://dev.perl.org/licenses/
version: 0.05
